### PR TITLE
Enable microphone by default.

### PR DESCRIPTION
**Pull request by anarsoul**
Credit goes to pfeerick for discovering right settings.

### CODE REVIEW

**Comment by ayufan** [comment]
@anarsoul Please fix the diff so we could see what did change :)

**Comment by anarsoul** [comment]
How? This is autogenerated file and I have no idea what version of alsa-utils was used to generate original. Fixing auto-generated files manually is not a good idea.

**Comment by pfeerick** [comment]
I'll look at this and submit a PR with just the changes in a day or three ;) Someone please kick me (gently!) if I forget! ;)

**Comment by ayufan** [comment]
@pfeerick kick :)

**Pull request closed without merging**
