### PR TITLE
Fix misspelled for pine64-model to pine64_model

### PR DESCRIPTION
**Pull request by sujunmin**

### CODE REVIEW

**Comment by pfeerick** [comment]
I'm actually wondering if it would be better the other way around... i.e. changing it at https://github.com/ayufan-pine64/linux-build/blob/master/simpleimage/make_rootfs.sh#L194 where it is a '_' instead of the '-' , as this will make it consistent with the device tree property... i.e. 

`/proc/device-tree/chosen/pine64-model`

(Had to dig through my emails to find it again, https://github.com/longsleep/u-boot-pine64/commit/cf0f2a7c4088131f35804e03c9a59d788c09246b#diff-05427d73f2e1d6dda5ee427f7c7be23e)

**Comment by Funmungus** [comment]
I would not know the best place, but if the file name is changed then so must the pine64_model references in /use/local/sbin/ scripts.

**Comment by pfeerick** [comment]
Yeah, true... meaning `pine64_upgrade_android.sh`, `pine64_install_to_emmc.sh` and `pine64_update_uboot.sh`  would need that changed as well.

**Comment by sujunmin** [comment]
Ok, I need to revoke this pr or to change them all?

**Comment by ayufan** [comment]
Yes, please

**Comment by sujunmin** [comment]
I found these 3 files (`pine64_upgrade_android.sh`, `pine64_install_to_emmc.sh` and `pine64_update_uboot.sh`) and there is only pine64_model (`cat /etc/pine64_model`), not pine64-model.

**Comment by ayufan** [comment]
Could you either update this PR or close it?

**Comment by sujunmin** [comment]
I've updated, I found these 3 files (`pine64_upgrade_android.sh`, `pine64_install_to_emmc.sh` and `pine64_update_uboot.sh`) and there is only pine64_model (`cat /etc/pine64_model`), not pine64-model.

**Comment by ayufan** [comment]
Awesome. Thanks :)

**Pull request merged**
